[profile.default]
optimizer = false                  # Enable or disable the solc optimizer
verbosity = 3                      # The verbosity of tests
rpc_endpoints = { mainnet = "${RPC_MAINNET}" }
fs_permissions = [
    { access = "read", path = "./broadcast/" }
]

[profile.production]
optimizer = true
optimizer_runs = 1_000_000
