[profile.default]
solc_version = "0.8.29"
evm_version = "cancun"
optimizer = false
verbosity = 3
fs_permissions = [
    { access = "read", path = "./broadcast/" }
]
via_ir = true

[profile.production]
optimizer = true
optimizer_runs = 1_000_000

[rpc_endpoints]
arbitrum = "${RPC_ARBITRUM}"
linea = "${RPC_LINEA}"
mainnet = "${RPC_MAINNET}"
optimism = "${RPC_OPTIMISM}"

[etherscan]
arbitrum = { key = "${ETHERSCAN_KEY_ARBITRUM}" }
linea = { key = "${ETHERSCAN_KEY_LINEA}" }
mainnet = { key = "${ETHERSCAN_KEY_MAINNET}" }
optimism = { key = "${ETHERSCAN_KEY_OPTIMISM}" }
