[profile.default]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = false
verbosity = 3
rpc_endpoints = { mainnet = "${RPC_MAINNET}" }
fs_permissions = [
    { access = "read", path = "./broadcast/" }
]

[profile.production]
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
